### ISSUE TITLE
128 G too small

### ISSUE THREAD

**Issue by NewtonBurger** [Dcarns/raspberrypifullnode#4]
I ran out of storage even on a 128 gig micro SD card. It was close though. It looks like a 200 gig would work and certainly a 256. 
It took. 2-3 days to sync, but appeared to be working ok. 
It would probably make more sense to put the data onto a USB peripheral rather than on the micro SD card.  Do you see a strong reason not to do that?  I'm sure writes are much slower, but the 200+G cards are pretty expensive.

Do you know if storing the blockchain on a USB device would work?  Is there a speed requirement for keeping it off of the ~ directory?  Do you know whether that is directly supported by the core code?

**Comment by flightmonkey15** [comment]
I came here for the same issue. Going through the steps here: http://www.raspberrypifullnode.com/

I have Raspberry Pi 3 the operating system is installed on a 32 gb micro sd card but I also have a 256 gb usb stick plugged in to use as file storage for the blockchain data. 

How do I get the Bitcoin full node setup using this configuration? 

When going through the install steps how do I point it to the usb stick instead of installing on the micro sd card?

Thanks for the help

**Comment by Dcarns** [comment]
I have not touched this project in years. Without dusting things off quite a bit, I would say the best route would be to go with a 200GB SD card (about $50)...which at least is cheaper than going to 256GB, which makes the cost jump to about $100.

I will update the website to reflect the 200GB SD card build.

**Comment by NewtonBurger** [comment]
Hi flightmonkey and Dcarns,

Setting a linux soft link to the .bitcoin folder to a device with more storage seems to work.  I've got a portable USB drive plugged into my pi.

[Here's a pretty good discussion,](https://bitzuma.com/posts/moving-the-bitcoin-core-data-directory/) covering different OSs with pictures etc.

I used the unix 'ln -s' command.  But it looks like you can specify an alternate location when you start up the app too.
